//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFClean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compact_detail
    {
        public string ServiceID { get; set; }
        public string CID { get; set; }
        public decimal Total_price { get; set; }
    
        public virtual Compact Compact { get; set; }
    }
}
