//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFClean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compact()
        {
            this.Compact_detail = new HashSet<Compact_detail>();
        }
    
        public string CID { get; set; }
        public string RID { get; set; }
        public string HID { get; set; }
        public string Signed_Date { get; set; }
        public string Work_Time { get; set; }
        public string ServiceID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compact_detail> Compact_detail { get; set; }
        public virtual Housekeeper Housekeeper { get; set; }
        public virtual Renter Renter { get; set; }
        public virtual Service Service { get; set; }
    }
}
