//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFClean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public string FbID { get; set; }
        public string Comment { get; set; }
        public string HID { get; set; }
        public string RID { get; set; }
        public string Rate { get; set; }
    
        public virtual Housekeeper Housekeeper { get; set; }
        public virtual Renter Renter { get; set; }
    }
}
